### ISSUE TITLE
示例代码无法运行

### ISSUE THREAD

**Issue by xqm32** [OneBST/GGanalysis#23]
## 运行环境

```
OS Version: macOS 14.0 arm64
Python Version: Python 3.11.4
```

`pip freeze` 结果：

```
contourpy==1.1.1
cycler==0.12.0
fonttools==4.43.0
kiwisolver==1.4.5
matplotlib==3.8.0
numpy==1.26.0
packaging==23.2
Pillow==10.0.1
pyparsing==3.1.1
python-dateutil==2.8.2
scipy==1.11.3
six==1.16.0
```

## 复现过程

代码：

https://github.com/OneBST/GGanalysis/blob/80191d981c024fb49389a717b034de3a8478e97a/readme.md?plain=1#L32-L43

运行结果：

```
角色池在垫了20抽，有大保底的情况下抽3个UP五星抽数的分布
Traceback (most recent call last):
  File "/Users/xqm/Develop/Python/GGanalysis/main.py", line 5, in <module>
    dist_c = GI.up_5star_character(item_num=3, pull_state=20, up_guarantee=1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xqm/Develop/Python/GGanalysis/GGanalysis/basic_models.py", line 201, in __call__
    return super().__call__(item_num, multi_dist, item_pity, up_pity, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xqm/Develop/Python/GGanalysis/GGanalysis/basic_models.py", line 20, in __call__
    parameter_list = self._build_parameter_list(*args, **kwds)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DualPityModel._build_parameter_list() got an unexpected keyword argument 'pull_state'
```

## 可能的原因

`DualPityModel` 中 `_build_parameter_list()` 方法没有 keyword argument `pull_state`:
https://github.com/OneBST/GGanalysis/blob/dff573c95308e16e450a3ba9e10868aa3351a7c0/GGanalysis/basic_models.py#L203-L208

而 `dist_c`[^1] 是一个 `DualPityModel`[^2]，`DualPityModel` 覆写了它的基类 `CommonGachaModel` 的 `_build_parameter_list()`[^3] 方法

[^1]: https://github.com/OneBST/GGanalysis/blob/80191d981c024fb49389a717b034de3a8478e97a/readme.md?plain=1#L36

[^2]: https://github.com/OneBST/GGanalysis/blob/d8fd30722743742a9774e6c97f2a76d83c769881/GGanalysis/games/genshin_impact/gacha_model.py#L60

[^3]: https://github.com/OneBST/GGanalysis/blob/dff573c95308e16e450a3ba9e10868aa3351a7c0/GGanalysis/basic_models.py#L34

**Comment by xqm32** [comment]
In this commit https://github.com/OneBST/GGanalysis/commit/d8fd30722743742a9774e6c97f2a76d83c769881, `pull_state` was renamed to `item_pity` and `up_guarantee` was renamed to `up_pity`, so this issue seems caused by outdated documentation. I will try to fix it.

@OneBST please review these changes #24, thanks!
